meta:
  defaultTitle: barthy.koeln
  titleSuffix: · Software Engineering
  defaultDescription: Software Engineering & Web Development
  imageUrl: https://barthy.koeln/images/meta-image.webp
  canonicalUrl: https://barthy.koeln