# Work experience data for RDFa schema.org markup

jobs:
  - employer: "Electronic Arts"
    roleName: "Software Engineer III"
    url: "https://ea.com"
    startDate: '2024-10-01'
    endDate: null
    description: "Senior position in an agile team exploring new technologies. Projects range from internal demos and prototypes to production-ready features for EA's games and services."
    keywords: "Gaming, Sports Media, Publishing"
    occupation: "Software Engineering"
    responsibilities:
      - "Coached 4 Software Engineer II"
      - "Modernized Content Publishing CMS with 14k+ existing entries"
      - "Implemented fast-paced online multiplayer game for handheld"
      - "Set up a knowledge exchange platform and filled it following the Diátaxis framework"
      - "Created agentic review processes in CI/CD"
      - "Implemented error monitoring and visual regression tools"
    techStack:
      - "Next.js"
      - "React"
      - "TypeScript"
      - "GDScript"
      - "Godot C++"

  - employer: "grandcentrix GmbH (Vodafone Group)"
    roleName: "Senior Web Developer"
    url: "https://web.archive.org/web/20250815053837/https://grandcentrix.net/"
    startDate: "2023-05-01"
    endDate: "2024-09-30"
    description: "Senior position taking ownership of frontend development and coordination with embedded and backend development for an IoT fleet management platform."
    keywords: "IoT, Fleet Management"
    occupation: "Web Development"
    achievements:
      - "Coached 3 junior/intermediate software engineers"
      - "Reduced page load times by 90% by enforcing strict coding guidelines, code reuse, and minimizing dependencies"
      - "Continuously improved e2e tests, reducing regression errors despite large refactoring"
      - "Empowered interdisciplinary exchange and planning through structured RFCs"
      - "Spun up a second product front-end within weeks thanks to loosely coupled architecture and reusable components"
      - "Created a bandwidth consumption calculator for IIoT application based on user config, firmware logic, data encoding and UDP transport"
    techStack:
      - "Node.js"
      - "Vue.js"
      - "TypeScript"

  - employer: "VUCX GmbH"
    roleName: "Head of Development"
    url: "https://vucx.de"
    startDate: "2020-08-01"
    endDate: "2023-04-30"
    description: "Led a development team within a full-service media and software agency."
    keywords: "Software, Media, CMS, CRM"
    occupation: "Software Engineering"
    responsibilities:
      - "Led 3 junior and mid-level developers, one promoted to senior"
      - "Led large-scale migration of public sector data into custom GDPR-compliant CMS"
      - "Developed interactive and discoverable search engines for ~1M daily visitors"
      - "Migrated monolithic servers to modern containerized cloud deployments"
      - "Architected and implemented multi-tenant / multi-site distributed CMs"
      - "Consulted international clients and third-party agencies"
    techStack:
      - "Symfony PHP"
      - "TypeScript"
      - "Vue.js"
      - "React"
      - "Next.js"

  - employer: "Freelance"
    roleName: "Web Development"
    url: "https://barthy.koeln/#freelance"
    startDate: "2014-01-01"
    endDate: "2026-02-28"
    description: "Development, hosting, and maintenance of interactive 3D experiences and CMS."
    keywords: "Freelance, Web Development, Interactive Experiences"
    occupation: "Web Development"
    achievements:
      - "Built serverless Shopify app serving ~140k monthly invocations"
      - "Built 3D and VR experiences used in museum tours"
    techStack:
      - "Symfony PHP"
      - "Vue.js"
      - "TypeScript"
      - "ThreeJS"
      - "PayloadCMS"
      - "Cloudflare Serverless"

  - employer: "VUCX GmbH"
    roleName: "Working Student Web Development"
    url: "https://vucx.de"
    startDate: "2014-06-01"
    endDate: "2020-07-31"
    description: "Hobbyist to full stack web developer."
    keywords: "Software, Media, CMS, CRM"
    occupation: "Web Development"
    techStack:
      - "Symfony PHP"
      - "Vue.js"
      - "TypeScript"
      - "JavaScript"

  - employer: "keinegrenzen.org"
    roleName: "Founder and Developer"
    url: "festival2019.keinegrenzen.org"
    startDate: "2014-04-04"
    endDate: "2020-12-31"
    description: "Charitable online platform exchanging underground artists' music for donations to Doctors without Borders."
    keywords: "Non-profit, Web, Event-Planning"
    occupation: "Web Development"
    techStack:
      - "Symfony PHP"
      - "Vue.js"
      - "JavaScript"